# Appendix A: Species seen\* in the hake fishery {.appendix}

See note about ASHOP program under data sources. The at-sea hake fishery does not fall under the WCGOP program.

\*not a definitive list

+------------------+---+------------------------------------+
| **ROCKFISH**     |   | **FLATFISH**                       |
+------------------+---+------------------------------------+
| \                | \ | \                                  |
+------------------+---+------------------------------------+
| **COMMON**       | \ | **COMMON**                         |
+------------------+---+------------------------------------+
| aurora           | \ | arrowtooth flounder                |
+------------------+---+------------------------------------+
| bank             | \ | dover sole                         |
+------------------+---+------------------------------------+
| blackspotted     | \ | English sole                       |
+------------------+---+------------------------------------+
| bocaccio         | \ | flathead sole                      |
+------------------+---+------------------------------------+
| canary           | \ | Pacific halibut                    |
+------------------+---+------------------------------------+
| chilipepper      | \ | Pacific sanddab                    |
+------------------+---+------------------------------------+
| darkblotched     | \ | petrale sole                       |
+------------------+---+------------------------------------+
| greenstriped     | \ | rex sole                           |
+------------------+---+------------------------------------+
| POP              | \ | slender sole                       |
+------------------+---+------------------------------------+
| redstripe        | \ | southern rock sole                 |
+------------------+---+------------------------------------+
| rougheye         | \ | \                                  |
+------------------+---+------------------------------------+
| sharpchin        | \ | **UNCOMMON**                       |
+------------------+---+------------------------------------+
| shortbelly       | \ | California halibut                 |
+------------------+---+------------------------------------+
| shortspine       | \ | \                                  |
+------------------+---+------------------------------------+
| silvergray       | \ | \                                  |
+------------------+---+------------------------------------+
| splitnose        | \ | **SHARKS, SKATES, RAYS & RATFISH** |
+------------------+---+------------------------------------+
| stripetail       | \ | \                                  |
+------------------+---+------------------------------------+
| widow            | \ | **COMMON**                         |
+------------------+---+------------------------------------+
| yellowtail       | \ | big skate                          |
+------------------+---+------------------------------------+
| \                | \ | blue shark                         |
+------------------+---+------------------------------------+
| **UNCOMMON**     | \ | brown cat shark                    |
+------------------+---+------------------------------------+
| black            | \ | longnose skate                     |
+------------------+---+------------------------------------+
| blackgill        | \ | Pacific electric ray               |
+------------------+---+------------------------------------+
| blue             | \ | salmon shark                       |
+------------------+---+------------------------------------+
| harlequin        | \ | sandpaper skate                    |
+------------------+---+------------------------------------+
| longspine        | \ | six gill shark                     |
+------------------+---+------------------------------------+
| quillback        | \ | soupfin shark                      |
+------------------+---+------------------------------------+
| redbanded        | \ | spiny dogfish shark                |
+------------------+---+------------------------------------+
| rosethorn        | \ | spotted ratfish                    |
+------------------+---+------------------------------------+
| speckled         | \ | thresher shark                     |
+------------------+---+------------------------------------+
| squarespot       | \ | \                                  |
+------------------+---+------------------------------------+
| tiger            | \ | \                                  |
+------------------+---+------------------------------------+
| yelloweye        | \ | **MISCELLANEOUS**                  |
+------------------+---+------------------------------------+
| yellowmouth      | \ | \                                  |
+------------------+---+------------------------------------+
| \                | \ | **COMMON**                         |
+------------------+---+------------------------------------+
| \                | \ | American shad                      |
+------------------+---+------------------------------------+
| **SALMON**       | \ | barracudinas                       |
+------------------+---+------------------------------------+
| \                | \ | jack mackeral                      |
+------------------+---+------------------------------------+
| **COMMON**       | \ | king-of-the-salmon                 |
+------------------+---+------------------------------------+
| Chinook          | \ | lamprey                            |
+------------------+---+------------------------------------+
| chum             | \ | lanternfish                        |
+------------------+---+------------------------------------+
| coho             | \ | lingcod                            |
+------------------+---+------------------------------------+
| pink (odd years) | \ | Pacific cod                        |
+------------------+---+------------------------------------+
| \                | \ | Pacific herring                    |
+------------------+---+------------------------------------+
| **UNCOMMON**     | \ | Pacific mackeral                   |
+------------------+---+------------------------------------+
| sockeye          | \ | Pacific sardine                    |
+------------------+---+------------------------------------+
| steelhead        | \ | pollock                            |
+------------------+---+------------------------------------+
| \                | \ | ragfish                            |
+------------------+---+------------------------------------+
| \                | \ | sablefish                          |
+------------------+---+------------------------------------+
