# Preface {.unnumbered}

**Note**: this is a document for use by the NWFSC and SWFSC groundfish stock assessment groups. Nothing in this document is guaranteed to be accurate or up-to-date, to work for any particular species, to write your model for you, or to save you from getting grilled at a STAR panel.\

Dear Reader,

This document is not intended to be followed blindly. Its purpose is to collect in an organized and accessible format some of the wisdom that has been accumulating in the heads of stock assessment authors ([see list of past assessments](https://docs.google.com/spreadsheets/d/18VIsx7qAZ6p80KSrxd1B-68KdGgZBu8QJPAkXVYrClE/edit#gid=1445731925)). Where reasonable alternative approaches can be used, they should be listed here, with indications of the pros and cons of each approach. If you think something is missing, please add it--this is a work in progress. If you would prefer that assessment authors all make independent, arbitrary decisions, uninformed by what's been done in the past, and unaware of the issues associated with different approaches, feel free to stop reading this document at any time. Otherwise, please don't criticize these notes in public meetings.

# Alternative sources for best practices

The SSC Groundfish Sub-committee has produced documents "ACCEPTED PRACTICES GUIDELINES FOR GROUNDFISH STOCK ASSESSMENTS". These documents, as well as the official groundfish stock assessment terms of reference (available at https://www.pcouncil.org/stock-assessments-star-reports-stat-reports-rebuilding-analyses-terms-of-reference/groundfish-stock-assessment-documents/), are both more up-to-date than this handbook and also carry more weight. However, they are also less comprehensive than this document. You should either follow their guidelines or be prepared to justify why you didn't.

-   [2023 version](https://www.pcouncil.org/documents/2023/12/accepted-practice-attachment-for-ssc-gfsc-january-17-18-2023.pdf/)

-   Older versions (perhaps useful for understanding the choices made in previous assessments): [2021](https://www.pcouncil.org/documents/2021/02/accepted-practices-and-guidelines-for-groundfish-stock-assessments-february-2021.pdf/), 
[2019](https://www.pcouncil.org/documents/2019/04/accepted-practices-and-guidelines-for-groundfish-stock-assessments-april-2019.pdf/), 
and [2017](https://www.pcouncil.org/documents/2017/04/accepted-practices-and-guidelines-for-groundfish-stock-assessments-revised-20-april-2017.pdf/)
